### PR TITLE
feat: mermaid graphs in markdown

### PR DESCRIPTION
**Pull request by abvthecity**
Screenshot 2024-09-19 at 9 34 08 PM

demo: https://app-devbuildwithfern-7zzgv3lsy-buildwithfern.vercel.app/api/fern-docs/preview?host=mermaid-test.docs.dev.buildwithfern.com (open this in localhost until the PR is merged)

### CODE REVIEW

**Comment by dsinghvi** [comment]
@chdeskur can you own documenting this custom component?

**Comment by dsinghvi** [comment]
@abvthecity can we add a fixture to the ete tests that @RohinBhargava setup? feels cheap and then we can make sure we dont regress on the feature

**Comment by abvthecity** [comment]
Yeah can do it next week

**Comment by chdeskur** [comment]
merged and re-tested: 

Screenshot 2024-10-23 at 3 43 42 PM

**Pull request merged**
